
// #define DEBUG

#define TYPE_VEST 701
#define TYPE_UNIFORM 801
#define TYPE_BACKPACK 901

#define BODY_PART_HEAD "head"
#define BODY_PART_ARMS "arms"
#define BODY_PART_TORSO "torso"
#define BODY_PART_LEGS "legs"
#define BODY_PARTS_ARR [BODY_PART_HEAD, BODY_PART_ARMS, BODY_PART_TORSO, BODY_PART_LEGS]

#define DMG_1 0.35
#define DMG_2 0.6
#define DMG_3 0.9

#define WOUND_MAX 3
#define WOUNDS_BLEED_THRESHOLD 6
