// This is automatically added by the build system
#include "common_includes.hpp"

class CfgPatches
{
    class ADDON
    {
        AUTHORSAVAGE;
        name = "server";
        url = "https://www.sogpf.com";
        units[] = {};
        weapons[] = {};
        requiredVersion = 2.18;
        requiredAddons[] = {};
    };
};

#define VGM_PATH PATH_LITERAL(\v\vgm_server\addons\server\)

// Generated by the build system.
class CfgFunctions {
    #include "built_functions.hpp"
};

// Generated by the build system.
#include "built_config.hpp"
