// This is automatically added by the build system
#include "common_includes.hpp"

class CfgPatches
{
    class vgm_server
    {
        AUTHORSAVAGE;
        name = "vgm_server";
        url = "https://www.sogpf.com";
        units[] = {};
        weapons[] = {};
        requiredVersion = 2.18;
        requiredAddons[] = {};
    };
};

// Generated by the build system.
#include "CfgFunctions.hpp"
#include "built_config.hpp"
