#include "inc\macros.inc"
#include "\a3\3den\UI\macroExecs.inc"
#include "inc\macroExecs.inc"
#include "controls.hpp"

// #include "VGM_DisplaySkills.hpp"
#include "VGM_DisplayAbilities.hpp"
// #include "VGM_DisplayMissions.hpp"
// #include "VGM_DisplayMissionsTargets.hpp"
#include "VGM_DisplayTest.hpp"
