[vgm]
displayName = "$STR_VGM_MISSION_NAME"

# Pages require a matching {pagename}.toml file.
pages = [
    "getting_started",
    "missions",
    "skills",
    "medical",
]

[vgm_missions]

displayName = ["%1 - Missions", "localize 'STR_VGM_MISSION_NAME'"]

pages = [
    "scouting"
]
