displayName = "Medical system"

# TODO: Fix arguments showing `anyanyany` for `{2}` (H keybind) and `{3}` (Shift + H keybind)

description = """
[h]{1}[/h] introduces simple yet impactful medical system featuring:
- Increased player durability
- Location-aware injuries that impact gameplay
- Slow bleed-out, if left untreated

<t size="1.25">Medical menu</t>
[h]Medical menu[/h] allows treatment of the injuries suffered by player characters.
To treat an injury you need to select an injured body part from the character [h]silhouette[/h] and apply [h]medication[/h] on it.
Press [h]H[/h] to open medical menu of the person you're looking at, if there's no person under your cursor the menu of your character will open.
Alternatively press [h]Shift + H[/h] to open the medical menu of your character.

<t size="1.1">Medication</t>
Available medication items:
- First Aid Kit - Heals single wound level, single use, can be used by anybody
- Medikit - Heals single wound level, infinite uses, can be used by players with "{4}" skill from the [h]Support[/h] tree

<t size="1.1">Debuffs</t>
Character injuries will affect your performance, the more severe injuries the stronger debuffs will be applied. Type of debuffs depend on the injured body parts:
- Head - TODO
- Torso - TODO
- Arms
- Legs - TODO
Multiple untreaded wounds will cause [h]bleeding[/h] which if not stopped will cause the character to fall [h]unconscious[/h].

<t size="1.1">Unconsciousnes</t>
After receiving critical amount of damage to vital body parts (head, torso) or bleeding out, the player character will fall [h]unconscious[/h], characters in this state need help of other players to wake up.
If the player will be abandoned and left alone by other players, he'll [h]respawn[/h].
Once all players in the mission are [h]unconscious[/h], the mission fails.
"""

tip = "Bullets. Shrapnel. Recon teams rarely made it out unscathed."

arguments = [
"localize 'STR_VGM_MISSION_NAME'",
"""
[
    ['OpenMedicalMenu'] call (missionNamespace getVariable 'para_c_fnc_keyhandler_getKeyBind'),
    true
] call (missionNamespace getVariable 'para_c_fnc_keyhandler_stringifyKeybind')
""",
"""
[
    ['OpenMedicalMenuSelf'] call (missionNamespace getVariable 'para_c_fnc_keyhandler_getKeyBind'),
    true
] call (missionNamespace getVariable 'para_c_fnc_keyhandler_stringifyKeybind')
""",
"localize 'STR_VGM_SKILLS_SKILL_SUPPORT_LOADOUT_MEDICAL'",
]

# Note that this is a literal string with ', so backslashes don't need escaping.
image = '\a3\ui_f\data\gui\cfg\hints\injury_ca.paa'
