displayName = "Extraction"
description = """
As the mission leader, you can call for extraction at any point during the mission.
This will call for a helicopter that will land a a nearby LZ. The mission will finish successfully once all non-incapacitated players are on-board.

See the [h]Missions[/h] field manual entry for more info.
"""

arguments = []

image = 'assets\atf_logo.paa'
