displayName = "You joined a mission"
description = """
You've joined another player's mission.
The leader can start the mission at any time. In the meantime, you're free to manage your gear and skills. You can leave the mission using the actions on the map board.

See the [h]Missions[/h] field manual entry for more info.
"""

arguments = []

image = 'assets\atf_logo.paa'
