displayName = "You created a mission"
description = """
You've just created a new mission! Other players will be able to join your mission until you depart. You can abort the mission by leaving the team, using the actions on the map board.

Make sure to check with your team before starting the mission, otherwise you might find them unprepared.

See the [h]Missions[/h] field manual entry for more info.
"""

arguments = []

image = 'assets\atf_logo.paa'
