name = "Across the Fence (Server)"
prefix = "vgm_server"
mainprefix = "v"

[properties]
author = "Savage Game Design"
url = "https://www.sogpf.com"

[version]
path = "addons/server/script_version.hpp"

[release]
sign = false
archive = true
