// This is automatically added to the server PBO
#include "common_includes.hpp"

class CfgPatches
{
    class vgm_server
    {
        AUTHORSAVAGE;
        name = "vgm_server";
        url = "https://www.sogpf.com";
        units[] = {};
        weapons[] = {};
        requiredVersion = 2.18;
        requiredAddons[] =
        {
        };
    };
};

// Automagically generated by the build system.
#include "CfgFunctions.hpp"
