name: ARMA Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT

    - name: Setup config
      run: cp build/config.example.py build/config.py

    - name: Run build script
      run: python build/run.py lint

    - name: Test
      run: |
        echo "::error file=paradigm/client/configs/ui/voting_menu/overlay.hpp,line=248,endLine=248,col=62,endColumn=74,title=macro's result could not be parsed::invalid macro result"
